pipeline:
  eslint:check:
    group: pr
    when:
      event: [pull_request, push]
    image: node:11.15.0
    commands:
      - npm install
      - npx lerna bootstrap
      - npm run prettier:check

  prettier:
    group: pr
    when:
      event: [pull_request, push]
    image: node:11.15.0
    commands:
      - npm install
      - npx lerna bootstrap
      - npm run prettier:check

  build:
    group: pr
    when:
      event: [pull_request, push]
    image: node:11.15.0
    commands:
      - npm install
      - npx lerna bootstrap
      - npx lerna run build