pipeline:
  install:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - npm install
      - npx lerna bootstrap --no-ci

  code_checks:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - npm run eslint:check
      - npm run prettier:check

  build:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - npx lerna run build

  publish:
    when:
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: [ "npm_token" ]
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npx lerna publish from-package --yes

  # send-percy:
  #   when:
  #     event: [push]
  #   image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
  #   secrets: [percy_token]
  #   commands:
  #     - npm run snapshot
