pipeline:
  fetch_tags:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - git fetch --tags

  install:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - npm install
      - npx lerna bootstrap --no-ci

  code_checks:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - ./scripts/check_code.sh

  send-code-check-failures-to-slack:
    when:
      event: [push]
      status: [failure]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: [slack_webhook]
    commands:
      - node ./scripts/slack_code_check_failed.js

  build:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - NODE_ENV=production npm run build

  publish:
    when:
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: ['npm_token']
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npx lerna publish from-package --yes

  send-percy-changed:
    when:
      event: [push]
      branch:
        exclude: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: [percy_token]
    commands:
      - npm run snapshot:changed

  send-percy-all:
    when:
      event: [push]
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: [percy_token]
    commands:
      - npm run snapshot

  check-unpublished:
    when:
      event: [push]
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    secrets: [slack_webhook]
    commands:
      - node ./scripts/slack-unpublished.js
