pipeline:
  install:
    when:
      event: [push]
    image: node:11.15.0
    commands:
      - npm install
      - npx lerna exec npm install
      - npx lerna bootstrap

  code_checks:
    when:
      event: [push]
    image: node:11.15.0
    commands:
      - npm run eslint:check
      - npm run prettier:check

  build:
    when:
      event: [push]
    image: node:11.15.0
    commands:
      - npx lerna run build

  test:
    when:
      event: [pull_request, push]
    image: node:11.15.0
    commands:
      - npm test
