pipeline:
  install:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer
    commands:
      - npm install
      - npx lerna exec npm install
      - npx lerna bootstrap

  code_checks:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer
    commands:
      - npm run eslint:check
      - npm run prettier:check

  build:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer
    commands:
      - npx lerna run build

  send-percy:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer
    commands:
      - npm run snapshot
