pipeline:
  fetch_tags:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - git fetch --tags

  cache-restore:
    when:
      event: push
    image: registry.usw.co/drone/cache:latest
    restore: true
    mount:
      - /npm-cache
    s3:
      bucket: uswitch-ci-cache
      region: eu-west-1

  install:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - mkdir /npm-cache
      - npm set cache /npm-cache
      - npm ci --prefer-offline
      - npx lerna bootstrap --no-ci
      - ls /npm-cache

  build-storybook:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - npm run build-storybook

  eslint:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: checks
    commands:
      - npm run eslint:check

  prettier:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: checks
    commands:
      - npm run prettier:check

  a11y:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: checks
    commands:
      - USE_STATIC_STORYBOOK=true npm run a11y

  build:
    when:
      event: [push]
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    commands:
      - NODE_ENV=production npm run build

  publish:
    when:
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: post
    secrets: ['npm_token']
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npx lerna publish from-package --yes

  send-percy-changed:
    when:
      event: [push]
      branch:
        exclude: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: post
    secrets: [percy_token]
    commands:
      - npm run snapshot:changed

  send-percy-all:
    when:
      event: [push]
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: post
    secrets: [percy_token]
    commands:
      - npm run snapshot

  check-unpublished:
    when:
      event: [push]
      branch: master
    image: registry.usw.co/cloud/node-12-puppeteer:03228dd2d438979e8973ec16351c4d7bc88f552e
    group: post
    secrets: [slack_webhook]
    commands:
      - node ./scripts/slack-unpublished.js

  cache-rebuild:
    when:
      event: push
    image: registry.usw.co/drone/cache:latest
    rebuild: true
    mount:
      - /npm-cache
    s3:
      bucket: uswitch-ci-cache
      region: eu-west-1