import { SerializedStyles } from '@emotion/core';
export declare const defaultFontFamily = "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", Arial, sans-serif";
export declare const heading2: SerializedStyles;
export declare const heading3: SerializedStyles;
export declare const label: SerializedStyles;
export declare const subheading: SerializedStyles;
export declare const inputFontSize = 16;
export declare const inputLineHeight = 1.33;
export declare const input: SerializedStyles;
export declare const text: SerializedStyles;
export declare const small: SerializedStyles;
export declare const linkText: SerializedStyles;
export declare const alertText: SerializedStyles;
export declare const noWrap: SerializedStyles;
