name: Publish

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git checkout master
      - run: git pull
      - run: git config --global user.email "ruxandra.anghel@rvu.co.uk"
      - run: git config --global user.name "Ruxandra Anghel"
      - run: npm install
      - run: npx lerna publish --conventional-commits --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

