name: "check my bundlephobia"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bundlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonathan-fielding/bundlephobia-pr-review@1.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          strict: false
          threshold: 1
