name: Publish packages
on:
  push:
    branches:
      - master
      - github-registry

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm ci
        npx lerna bootstrap --no-ci

    - name: Build
      run: npm run build

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@uswitch'

    # - name: Authenticate with the GitHub Package Registry
    #   run: |
    #     echo "@uswitch:registry=https://npm.pkg.github.com/" > ~/.npmrc
    #     echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3

    - name: Lerna publish
      run: npx lerna publish from-package --yes --registry="https://npm.pkg.github.com/"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
